module.exports = [
  ['sequence_diagram', 'Markdown 进阶：时序图'],
  ['event_loop', '一道面试题引发的血案'],
  ['ca', '数字证书那些事'],
  ['fe_project', '前端工程化'],
  ['module', 'es6 模块化与 node 的模块化'],
  ['sentry', '给你的项目装个探头 — Sentry'],
  ['spa', '大话 SPA router'],
  ['async_await_for', 'async、await 在 for 循环里怎么样？'],
  ['timing_attack', 'Timing Attack'],
  ['type_change', 'JS 看不懂的 []+{}'],
  ['webpack', '换个角度学 Webpack'],
  ['grid', 'Grid 布局发车啦'],
  ['http_cache', 'Http 缓存那些事'],
  ['write_readme', '怎么写一个高逼格的 README'],
  ['stream', '流“忙”'],
  ['performance', '试炼之石 - Performance'],
  ['2018to2019', '2018 年终总结'],
  ['babel_plugin', '你会 babel 插件么？我也不会'],
  ['base64', 'Base64 编码'],
  ['css_ellipsis', 'CSS 实现单行文本、多行文本溢出省略号'],
  ['dsa', '数据结构与算法'],
  ['eslint_rule', 'ESLint 校验规则集的思考'],
  ['generator', 'ES6 之 generator'],
  ['react_hoc', 'React 高阶组件'],
  ['react_mixin_hooks', 'React Mixin 到 Hooks'],
  ['mongodb_transaction', 'MongoDB 中的事务'],
  ['docker_volumn_cover', 'Docker volumn 被覆盖了？'],
  ['7_habits', '高效程序员的 7 个技巧'],
  ['11_js_tricks', '11 个 JavaScript 技巧'],
  ['fcc_frontEnd_2018', 'FCC 2018 前端技术大会总结'],
];
